# Parametros de abertura de arquivos:
# 'r' - Modo de leitura (padrão)
# 'w' - Modo de escrita (cria um novo arquivo ou sobrescreve um arquivo existente)
# 'a' - Modo de anexação (adiciona conteúdo a um arquivo existente)
# 'b' - Modo binário (usado para arquivos binários, como imagens ou arquivos de áudio)
# 't' - Modo de texto (padrão para arquivos de texto)
# 'x' - Modo de criação exclusiva (cria um novo arquivo, mas falha se o arquivo já existir)
# 'r+' - Modo de leitura e escrita (permite ler e escrever em um arquivo existente)
# 'w+' - Modo de escrita e leitura (cria um novo arquivo ou sobrescreve um arquivo existente, permitindo ler e escrever)
# 'a+' - Modo de anexação e leitura (adiciona conteúdo a um arquivo existente, permitindo ler e escrever)
# 'x+' - Modo de criação exclusiva e leitura (cria um novo arquivo, mas falha se o arquivo já existir, permitindo ler e escrever)
# 'rt' - Modo de leitura em texto (padrão para arquivos de texto)
# 'rb' - Modo de leitura em binário (usado para arquivos binários)
# 'wt' - Modo de escrita em texto (cria um novo arquivo ou sobrescreve um arquivo existente)
# 'wb' - Modo de escrita em binário (usado para arquivos binários)
# 'at' - Modo de anexação em texto (adiciona conteúdo a um arquivo existente)
# 'ab' - Modo de anexação em binário (usado para arquivos binários)
# 'xt' - Modo de criação exclusiva em texto (cria um novo arquivo, mas falha se o arquivo já existir)
# 'xb' - Modo de criação exclusiva em binário (usado para arquivos binários)